name: worker_productivity_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - joblib>=1.1.0
  - pip:
      - mlflow==2.19.0
      - dagshub>=0.3.0
